// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/control.proto

package aeromq

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartbeatGroupResponse_Status int32

const (
	HeartbeatGroupResponse_OK                    HeartbeatGroupResponse_Status = 0
	HeartbeatGroupResponse_REBALANCE_IN_PROGRESS HeartbeatGroupResponse_Status = 1
	HeartbeatGroupResponse_UNKNOWN_MEMBER        HeartbeatGroupResponse_Status = 2
)

// Enum value maps for HeartbeatGroupResponse_Status.
var (
	HeartbeatGroupResponse_Status_name = map[int32]string{
		0: "OK",
		1: "REBALANCE_IN_PROGRESS",
		2: "UNKNOWN_MEMBER",
	}
	HeartbeatGroupResponse_Status_value = map[string]int32{
		"OK":                    0,
		"REBALANCE_IN_PROGRESS": 1,
		"UNKNOWN_MEMBER":        2,
	}
)

func (x HeartbeatGroupResponse_Status) Enum() *HeartbeatGroupResponse_Status {
	p := new(HeartbeatGroupResponse_Status)
	*p = x
	return p
}

func (x HeartbeatGroupResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeartbeatGroupResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_control_proto_enumTypes[0].Descriptor()
}

func (HeartbeatGroupResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_control_proto_enumTypes[0]
}

func (x HeartbeatGroupResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeartbeatGroupResponse_Status.Descriptor instead.
func (HeartbeatGroupResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{16, 0}
}

type BrokerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerId      uint32                 `protobuf:"varint,1,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerInfo) Reset() {
	*x = BrokerInfo{}
	mi := &file_proto_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerInfo) ProtoMessage() {}

func (x *BrokerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerInfo.ProtoReflect.Descriptor instead.
func (*BrokerInfo) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{0}
}

func (x *BrokerInfo) GetBrokerId() uint32 {
	if x != nil {
		return x.BrokerId
	}
	return 0
}

func (x *BrokerInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *BrokerInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type PartitionAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     uint32                 `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	LeaderId      uint32                 `protobuf:"varint,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	ReplicaIds    []uint32               `protobuf:"varint,4,rep,packed,name=replica_ids,json=replicaIds,proto3" json:"replica_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionAssignment) Reset() {
	*x = PartitionAssignment{}
	mi := &file_proto_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionAssignment) ProtoMessage() {}

func (x *PartitionAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionAssignment.ProtoReflect.Descriptor instead.
func (*PartitionAssignment) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{1}
}

func (x *PartitionAssignment) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PartitionAssignment) GetPartition() uint32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *PartitionAssignment) GetLeaderId() uint32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *PartitionAssignment) GetReplicaIds() []uint32 {
	if x != nil {
		return x.ReplicaIds
	}
	return nil
}

// Broker registrations
type RegisterBrokerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerId      uint32                 `protobuf:"varint,1,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	DataPort      int32                  `protobuf:"varint,3,opt,name=data_port,json=dataPort,proto3" json:"data_port,omitempty"` // The port where the Rust broker listens for TCP data connections
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBrokerRequest) Reset() {
	*x = RegisterBrokerRequest{}
	mi := &file_proto_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBrokerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBrokerRequest) ProtoMessage() {}

func (x *RegisterBrokerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBrokerRequest.ProtoReflect.Descriptor instead.
func (*RegisterBrokerRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterBrokerRequest) GetBrokerId() uint32 {
	if x != nil {
		return x.BrokerId
	}
	return 0
}

func (x *RegisterBrokerRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RegisterBrokerRequest) GetDataPort() int32 {
	if x != nil {
		return x.DataPort
	}
	return 0
}

type RegisterBrokerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBrokerResponse) Reset() {
	*x = RegisterBrokerResponse{}
	mi := &file_proto_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBrokerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBrokerResponse) ProtoMessage() {}

func (x *RegisterBrokerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBrokerResponse.ProtoReflect.Descriptor instead.
func (*RegisterBrokerResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterBrokerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterBrokerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReplicaOffset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     uint32                 `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaOffset) Reset() {
	*x = ReplicaOffset{}
	mi := &file_proto_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaOffset) ProtoMessage() {}

func (x *ReplicaOffset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaOffset.ProtoReflect.Descriptor instead.
func (*ReplicaOffset) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{4}
}

func (x *ReplicaOffset) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ReplicaOffset) GetPartition() uint32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *ReplicaOffset) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BrokerId       uint32                 `protobuf:"varint,1,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	DiskUsageBytes uint64                 `protobuf:"varint,2,opt,name=disk_usage_bytes,json=diskUsageBytes,proto3" json:"disk_usage_bytes,omitempty"`
	DiskFreeBytes  uint64                 `protobuf:"varint,3,opt,name=disk_free_bytes,json=diskFreeBytes,proto3" json:"disk_free_bytes,omitempty"`
	ReplicaOffsets []*ReplicaOffset       `protobuf:"bytes,4,rep,name=replica_offsets,json=replicaOffsets,proto3" json:"replica_offsets,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatRequest) GetBrokerId() uint32 {
	if x != nil {
		return x.BrokerId
	}
	return 0
}

func (x *HeartbeatRequest) GetDiskUsageBytes() uint64 {
	if x != nil {
		return x.DiskUsageBytes
	}
	return 0
}

func (x *HeartbeatRequest) GetDiskFreeBytes() uint64 {
	if x != nil {
		return x.DiskFreeBytes
	}
	return 0
}

func (x *HeartbeatRequest) GetReplicaOffsets() []*ReplicaOffset {
	if x != nil {
		return x.ReplicaOffsets
	}
	return nil
}

type HeartbeatResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// The controller sends back the list of partitions this broker is assigned to lead or replicate
	AssignedLeaders   []*PartitionAssignment `protobuf:"bytes,2,rep,name=assigned_leaders,json=assignedLeaders,proto3" json:"assigned_leaders,omitempty"`
	AssignedFollowers []*PartitionAssignment `protobuf:"bytes,3,rep,name=assigned_followers,json=assignedFollowers,proto3" json:"assigned_followers,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetAssignedLeaders() []*PartitionAssignment {
	if x != nil {
		return x.AssignedLeaders
	}
	return nil
}

func (x *HeartbeatResponse) GetAssignedFollowers() []*PartitionAssignment {
	if x != nil {
		return x.AssignedFollowers
	}
	return nil
}

// Metadata queries
type MetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_proto_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{7}
}

func (x *MetadataRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

type MetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brokers       []*BrokerInfo          `protobuf:"bytes,1,rep,name=brokers,proto3" json:"brokers,omitempty"`
	Topics        []*TopicMetadata       `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	mi := &file_proto_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResponse.ProtoReflect.Descriptor instead.
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{8}
}

func (x *MetadataResponse) GetBrokers() []*BrokerInfo {
	if x != nil {
		return x.Brokers
	}
	return nil
}

func (x *MetadataResponse) GetTopics() []*TopicMetadata {
	if x != nil {
		return x.Topics
	}
	return nil
}

type TopicMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partitions    []*PartitionMetadata   `protobuf:"bytes,2,rep,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicMetadata) Reset() {
	*x = TopicMetadata{}
	mi := &file_proto_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicMetadata) ProtoMessage() {}

func (x *TopicMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicMetadata.ProtoReflect.Descriptor instead.
func (*TopicMetadata) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{9}
}

func (x *TopicMetadata) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *TopicMetadata) GetPartitions() []*PartitionMetadata {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type PartitionMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PartitionId    uint32                 `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	LeaderId       uint32                 `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	ReplicaIds     []uint32               `protobuf:"varint,3,rep,packed,name=replica_ids,json=replicaIds,proto3" json:"replica_ids,omitempty"`
	Isr            []uint32               `protobuf:"varint,4,rep,packed,name=isr,proto3" json:"isr,omitempty"`
	HighWatermark  int64                  `protobuf:"varint,5,opt,name=high_watermark,json=highWatermark,proto3" json:"high_watermark,omitempty"`
	ReplicaOffsets map[uint32]int64       `protobuf:"bytes,6,rep,name=replica_offsets,json=replicaOffsets,proto3" json:"replica_offsets,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PartitionMetadata) Reset() {
	*x = PartitionMetadata{}
	mi := &file_proto_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionMetadata) ProtoMessage() {}

func (x *PartitionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionMetadata.ProtoReflect.Descriptor instead.
func (*PartitionMetadata) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{10}
}

func (x *PartitionMetadata) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *PartitionMetadata) GetLeaderId() uint32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *PartitionMetadata) GetReplicaIds() []uint32 {
	if x != nil {
		return x.ReplicaIds
	}
	return nil
}

func (x *PartitionMetadata) GetIsr() []uint32 {
	if x != nil {
		return x.Isr
	}
	return nil
}

func (x *PartitionMetadata) GetHighWatermark() int64 {
	if x != nil {
		return x.HighWatermark
	}
	return 0
}

func (x *PartitionMetadata) GetReplicaOffsets() map[uint32]int64 {
	if x != nil {
		return x.ReplicaOffsets
	}
	return nil
}

// Create Topic (for admin/producer discovery facilitation)
type CreateTopicRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Topic             string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partitions        uint32                 `protobuf:"varint,2,opt,name=partitions,proto3" json:"partitions,omitempty"`
	ReplicationFactor uint32                 `protobuf:"varint,3,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_proto_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{11}
}

func (x *CreateTopicRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CreateTopicRequest) GetPartitions() uint32 {
	if x != nil {
		return x.Partitions
	}
	return 0
}

func (x *CreateTopicRequest) GetReplicationFactor() uint32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

type CreateTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicResponse) Reset() {
	*x = CreateTopicResponse{}
	mi := &file_proto_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicResponse) ProtoMessage() {}

func (x *CreateTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicResponse.ProtoReflect.Descriptor instead.
func (*CreateTopicResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{12}
}

func (x *CreateTopicResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateTopicResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Consumer Group management
type JoinGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"` // Empty if joining for the first time
	Topics        []string               `protobuf:"bytes,3,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGroupRequest) Reset() {
	*x = JoinGroupRequest{}
	mi := &file_proto_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupRequest) ProtoMessage() {}

func (x *JoinGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupRequest.ProtoReflect.Descriptor instead.
func (*JoinGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{13}
}

func (x *JoinGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *JoinGroupRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *JoinGroupRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

type JoinGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	GenerationId  uint32                 `protobuf:"varint,2,opt,name=generation_id,json=generationId,proto3" json:"generation_id,omitempty"`
	Assignments   []*PartitionAssignment `protobuf:"bytes,3,rep,name=assignments,proto3" json:"assignments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGroupResponse) Reset() {
	*x = JoinGroupResponse{}
	mi := &file_proto_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupResponse) ProtoMessage() {}

func (x *JoinGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupResponse.ProtoReflect.Descriptor instead.
func (*JoinGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{14}
}

func (x *JoinGroupResponse) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *JoinGroupResponse) GetGenerationId() uint32 {
	if x != nil {
		return x.GenerationId
	}
	return 0
}

func (x *JoinGroupResponse) GetAssignments() []*PartitionAssignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

type HeartbeatGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	GenerationId  uint32                 `protobuf:"varint,3,opt,name=generation_id,json=generationId,proto3" json:"generation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatGroupRequest) Reset() {
	*x = HeartbeatGroupRequest{}
	mi := &file_proto_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatGroupRequest) ProtoMessage() {}

func (x *HeartbeatGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatGroupRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{15}
}

func (x *HeartbeatGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *HeartbeatGroupRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *HeartbeatGroupRequest) GetGenerationId() uint32 {
	if x != nil {
		return x.GenerationId
	}
	return 0
}

type HeartbeatGroupResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Status        HeartbeatGroupResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=aeromq.HeartbeatGroupResponse_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatGroupResponse) Reset() {
	*x = HeartbeatGroupResponse{}
	mi := &file_proto_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatGroupResponse) ProtoMessage() {}

func (x *HeartbeatGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatGroupResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{16}
}

func (x *HeartbeatGroupResponse) GetStatus() HeartbeatGroupResponse_Status {
	if x != nil {
		return x.Status
	}
	return HeartbeatGroupResponse_OK
}

type TopicPartitionOffset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     uint32                 `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicPartitionOffset) Reset() {
	*x = TopicPartitionOffset{}
	mi := &file_proto_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicPartitionOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicPartitionOffset) ProtoMessage() {}

func (x *TopicPartitionOffset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicPartitionOffset.ProtoReflect.Descriptor instead.
func (*TopicPartitionOffset) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{17}
}

func (x *TopicPartitionOffset) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *TopicPartitionOffset) GetPartition() uint32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *TopicPartitionOffset) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CommitOffsetsRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	GroupId       string                  `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	MemberId      string                  `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	GenerationId  uint32                  `protobuf:"varint,3,opt,name=generation_id,json=generationId,proto3" json:"generation_id,omitempty"`
	Offsets       []*TopicPartitionOffset `protobuf:"bytes,4,rep,name=offsets,proto3" json:"offsets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOffsetsRequest) Reset() {
	*x = CommitOffsetsRequest{}
	mi := &file_proto_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOffsetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOffsetsRequest) ProtoMessage() {}

func (x *CommitOffsetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOffsetsRequest.ProtoReflect.Descriptor instead.
func (*CommitOffsetsRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{18}
}

func (x *CommitOffsetsRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CommitOffsetsRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *CommitOffsetsRequest) GetGenerationId() uint32 {
	if x != nil {
		return x.GenerationId
	}
	return 0
}

func (x *CommitOffsetsRequest) GetOffsets() []*TopicPartitionOffset {
	if x != nil {
		return x.Offsets
	}
	return nil
}

type CommitOffsetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOffsetsResponse) Reset() {
	*x = CommitOffsetsResponse{}
	mi := &file_proto_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOffsetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOffsetsResponse) ProtoMessage() {}

func (x *CommitOffsetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOffsetsResponse.ProtoReflect.Descriptor instead.
func (*CommitOffsetsResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{19}
}

func (x *CommitOffsetsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type FetchOffsetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Topics        []string               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchOffsetsRequest) Reset() {
	*x = FetchOffsetsRequest{}
	mi := &file_proto_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchOffsetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOffsetsRequest) ProtoMessage() {}

func (x *FetchOffsetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOffsetsRequest.ProtoReflect.Descriptor instead.
func (*FetchOffsetsRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{20}
}

func (x *FetchOffsetsRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *FetchOffsetsRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

type FetchOffsetsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Offsets       []*TopicPartitionOffset `protobuf:"bytes,1,rep,name=offsets,proto3" json:"offsets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchOffsetsResponse) Reset() {
	*x = FetchOffsetsResponse{}
	mi := &file_proto_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchOffsetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOffsetsResponse) ProtoMessage() {}

func (x *FetchOffsetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOffsetsResponse.ProtoReflect.Descriptor instead.
func (*FetchOffsetsResponse) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{21}
}

func (x *FetchOffsetsResponse) GetOffsets() []*TopicPartitionOffset {
	if x != nil {
		return x.Offsets
	}
	return nil
}

var File_proto_control_proto protoreflect.FileDescriptor

const file_proto_control_proto_rawDesc = "" +
	"\n" +
	"\x13proto/control.proto\x12\x06aeromq\"Q\n" +
	"\n" +
	"BrokerInfo\x12\x1b\n" +
	"\tbroker_id\x18\x01 \x01(\rR\bbrokerId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"\x87\x01\n" +
	"\x13PartitionAssignment\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\rR\tpartition\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\rR\bleaderId\x12\x1f\n" +
	"\vreplica_ids\x18\x04 \x03(\rR\n" +
	"replicaIds\"e\n" +
	"\x15RegisterBrokerRequest\x12\x1b\n" +
	"\tbroker_id\x18\x01 \x01(\rR\bbrokerId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x1b\n" +
	"\tdata_port\x18\x03 \x01(\x05R\bdataPort\"L\n" +
	"\x16RegisterBrokerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"[\n" +
	"\rReplicaOffset\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\rR\tpartition\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"\xc1\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tbroker_id\x18\x01 \x01(\rR\bbrokerId\x12(\n" +
	"\x10disk_usage_bytes\x18\x02 \x01(\x04R\x0ediskUsageBytes\x12&\n" +
	"\x0fdisk_free_bytes\x18\x03 \x01(\x04R\rdiskFreeBytes\x12>\n" +
	"\x0freplica_offsets\x18\x04 \x03(\v2\x15.aeromq.ReplicaOffsetR\x0ereplicaOffsets\"\xc1\x01\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12F\n" +
	"\x10assigned_leaders\x18\x02 \x03(\v2\x1b.aeromq.PartitionAssignmentR\x0fassignedLeaders\x12J\n" +
	"\x12assigned_followers\x18\x03 \x03(\v2\x1b.aeromq.PartitionAssignmentR\x11assignedFollowers\")\n" +
	"\x0fMetadataRequest\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics\"o\n" +
	"\x10MetadataResponse\x12,\n" +
	"\abrokers\x18\x01 \x03(\v2\x12.aeromq.BrokerInfoR\abrokers\x12-\n" +
	"\x06topics\x18\x02 \x03(\v2\x15.aeromq.TopicMetadataR\x06topics\"`\n" +
	"\rTopicMetadata\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x129\n" +
	"\n" +
	"partitions\x18\x02 \x03(\v2\x19.aeromq.PartitionMetadataR\n" +
	"partitions\"\xc8\x02\n" +
	"\x11PartitionMetadata\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\rR\vpartitionId\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\rR\bleaderId\x12\x1f\n" +
	"\vreplica_ids\x18\x03 \x03(\rR\n" +
	"replicaIds\x12\x10\n" +
	"\x03isr\x18\x04 \x03(\rR\x03isr\x12%\n" +
	"\x0ehigh_watermark\x18\x05 \x01(\x03R\rhighWatermark\x12V\n" +
	"\x0freplica_offsets\x18\x06 \x03(\v2-.aeromq.PartitionMetadata.ReplicaOffsetsEntryR\x0ereplicaOffsets\x1aA\n" +
	"\x13ReplicaOffsetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"y\n" +
	"\x12CreateTopicRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1e\n" +
	"\n" +
	"partitions\x18\x02 \x01(\rR\n" +
	"partitions\x12-\n" +
	"\x12replication_factor\x18\x03 \x01(\rR\x11replicationFactor\"I\n" +
	"\x13CreateTopicResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"b\n" +
	"\x10JoinGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12\x16\n" +
	"\x06topics\x18\x03 \x03(\tR\x06topics\"\x94\x01\n" +
	"\x11JoinGroupResponse\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12#\n" +
	"\rgeneration_id\x18\x02 \x01(\rR\fgenerationId\x12=\n" +
	"\vassignments\x18\x03 \x03(\v2\x1b.aeromq.PartitionAssignmentR\vassignments\"t\n" +
	"\x15HeartbeatGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12#\n" +
	"\rgeneration_id\x18\x03 \x01(\rR\fgenerationId\"\x98\x01\n" +
	"\x16HeartbeatGroupResponse\x12=\n" +
	"\x06status\x18\x01 \x01(\x0e2%.aeromq.HeartbeatGroupResponse.StatusR\x06status\"?\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\x19\n" +
	"\x15REBALANCE_IN_PROGRESS\x10\x01\x12\x12\n" +
	"\x0eUNKNOWN_MEMBER\x10\x02\"b\n" +
	"\x14TopicPartitionOffset\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\rR\tpartition\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"\xab\x01\n" +
	"\x14CommitOffsetsRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12#\n" +
	"\rgeneration_id\x18\x03 \x01(\rR\fgenerationId\x126\n" +
	"\aoffsets\x18\x04 \x03(\v2\x1c.aeromq.TopicPartitionOffsetR\aoffsets\"1\n" +
	"\x15CommitOffsetsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"H\n" +
	"\x13FetchOffsetsRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\tR\x06topics\"N\n" +
	"\x14FetchOffsetsResponse\x126\n" +
	"\aoffsets\x18\x01 \x03(\v2\x1c.aeromq.TopicPartitionOffsetR\aoffsets2\xa3\x01\n" +
	"\x0eControlService\x12O\n" +
	"\x0eRegisterBroker\x12\x1d.aeromq.RegisterBrokerRequest\x1a\x1e.aeromq.RegisterBrokerResponse\x12@\n" +
	"\tHeartbeat\x12\x18.aeromq.HeartbeatRequest\x1a\x19.aeromq.HeartbeatResponse2\xc8\x03\n" +
	"\x10DiscoveryService\x12@\n" +
	"\vGetMetadata\x12\x17.aeromq.MetadataRequest\x1a\x18.aeromq.MetadataResponse\x12@\n" +
	"\tJoinGroup\x12\x18.aeromq.JoinGroupRequest\x1a\x19.aeromq.JoinGroupResponse\x12O\n" +
	"\x0eHeartbeatGroup\x12\x1d.aeromq.HeartbeatGroupRequest\x1a\x1e.aeromq.HeartbeatGroupResponse\x12L\n" +
	"\rCommitOffsets\x12\x1c.aeromq.CommitOffsetsRequest\x1a\x1d.aeromq.CommitOffsetsResponse\x12I\n" +
	"\fFetchOffsets\x12\x1b.aeromq.FetchOffsetsRequest\x1a\x1c.aeromq.FetchOffsetsResponse\x12F\n" +
	"\vCreateTopic\x12\x1a.aeromq.CreateTopicRequest\x1a\x1b.aeromq.CreateTopicResponseB;Z9github.com/gradientgeeks/aeromq/go-controller/proto/aeromqb\x06proto3"

var (
	file_proto_control_proto_rawDescOnce sync.Once
	file_proto_control_proto_rawDescData []byte
)

func file_proto_control_proto_rawDescGZIP() []byte {
	file_proto_control_proto_rawDescOnce.Do(func() {
		file_proto_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_control_proto_rawDesc), len(file_proto_control_proto_rawDesc)))
	})
	return file_proto_control_proto_rawDescData
}

var file_proto_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_control_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_control_proto_goTypes = []any{
	(HeartbeatGroupResponse_Status)(0), // 0: aeromq.HeartbeatGroupResponse.Status
	(*BrokerInfo)(nil),                 // 1: aeromq.BrokerInfo
	(*PartitionAssignment)(nil),        // 2: aeromq.PartitionAssignment
	(*RegisterBrokerRequest)(nil),      // 3: aeromq.RegisterBrokerRequest
	(*RegisterBrokerResponse)(nil),     // 4: aeromq.RegisterBrokerResponse
	(*ReplicaOffset)(nil),              // 5: aeromq.ReplicaOffset
	(*HeartbeatRequest)(nil),           // 6: aeromq.HeartbeatRequest
	(*HeartbeatResponse)(nil),          // 7: aeromq.HeartbeatResponse
	(*MetadataRequest)(nil),            // 8: aeromq.MetadataRequest
	(*MetadataResponse)(nil),           // 9: aeromq.MetadataResponse
	(*TopicMetadata)(nil),              // 10: aeromq.TopicMetadata
	(*PartitionMetadata)(nil),          // 11: aeromq.PartitionMetadata
	(*CreateTopicRequest)(nil),         // 12: aeromq.CreateTopicRequest
	(*CreateTopicResponse)(nil),        // 13: aeromq.CreateTopicResponse
	(*JoinGroupRequest)(nil),           // 14: aeromq.JoinGroupRequest
	(*JoinGroupResponse)(nil),          // 15: aeromq.JoinGroupResponse
	(*HeartbeatGroupRequest)(nil),      // 16: aeromq.HeartbeatGroupRequest
	(*HeartbeatGroupResponse)(nil),     // 17: aeromq.HeartbeatGroupResponse
	(*TopicPartitionOffset)(nil),       // 18: aeromq.TopicPartitionOffset
	(*CommitOffsetsRequest)(nil),       // 19: aeromq.CommitOffsetsRequest
	(*CommitOffsetsResponse)(nil),      // 20: aeromq.CommitOffsetsResponse
	(*FetchOffsetsRequest)(nil),        // 21: aeromq.FetchOffsetsRequest
	(*FetchOffsetsResponse)(nil),       // 22: aeromq.FetchOffsetsResponse
	nil,                                // 23: aeromq.PartitionMetadata.ReplicaOffsetsEntry
}
var file_proto_control_proto_depIdxs = []int32{
	5,  // 0: aeromq.HeartbeatRequest.replica_offsets:type_name -> aeromq.ReplicaOffset
	2,  // 1: aeromq.HeartbeatResponse.assigned_leaders:type_name -> aeromq.PartitionAssignment
	2,  // 2: aeromq.HeartbeatResponse.assigned_followers:type_name -> aeromq.PartitionAssignment
	1,  // 3: aeromq.MetadataResponse.brokers:type_name -> aeromq.BrokerInfo
	10, // 4: aeromq.MetadataResponse.topics:type_name -> aeromq.TopicMetadata
	11, // 5: aeromq.TopicMetadata.partitions:type_name -> aeromq.PartitionMetadata
	23, // 6: aeromq.PartitionMetadata.replica_offsets:type_name -> aeromq.PartitionMetadata.ReplicaOffsetsEntry
	2,  // 7: aeromq.JoinGroupResponse.assignments:type_name -> aeromq.PartitionAssignment
	0,  // 8: aeromq.HeartbeatGroupResponse.status:type_name -> aeromq.HeartbeatGroupResponse.Status
	18, // 9: aeromq.CommitOffsetsRequest.offsets:type_name -> aeromq.TopicPartitionOffset
	18, // 10: aeromq.FetchOffsetsResponse.offsets:type_name -> aeromq.TopicPartitionOffset
	3,  // 11: aeromq.ControlService.RegisterBroker:input_type -> aeromq.RegisterBrokerRequest
	6,  // 12: aeromq.ControlService.Heartbeat:input_type -> aeromq.HeartbeatRequest
	8,  // 13: aeromq.DiscoveryService.GetMetadata:input_type -> aeromq.MetadataRequest
	14, // 14: aeromq.DiscoveryService.JoinGroup:input_type -> aeromq.JoinGroupRequest
	16, // 15: aeromq.DiscoveryService.HeartbeatGroup:input_type -> aeromq.HeartbeatGroupRequest
	19, // 16: aeromq.DiscoveryService.CommitOffsets:input_type -> aeromq.CommitOffsetsRequest
	21, // 17: aeromq.DiscoveryService.FetchOffsets:input_type -> aeromq.FetchOffsetsRequest
	12, // 18: aeromq.DiscoveryService.CreateTopic:input_type -> aeromq.CreateTopicRequest
	4,  // 19: aeromq.ControlService.RegisterBroker:output_type -> aeromq.RegisterBrokerResponse
	7,  // 20: aeromq.ControlService.Heartbeat:output_type -> aeromq.HeartbeatResponse
	9,  // 21: aeromq.DiscoveryService.GetMetadata:output_type -> aeromq.MetadataResponse
	15, // 22: aeromq.DiscoveryService.JoinGroup:output_type -> aeromq.JoinGroupResponse
	17, // 23: aeromq.DiscoveryService.HeartbeatGroup:output_type -> aeromq.HeartbeatGroupResponse
	20, // 24: aeromq.DiscoveryService.CommitOffsets:output_type -> aeromq.CommitOffsetsResponse
	22, // 25: aeromq.DiscoveryService.FetchOffsets:output_type -> aeromq.FetchOffsetsResponse
	13, // 26: aeromq.DiscoveryService.CreateTopic:output_type -> aeromq.CreateTopicResponse
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_control_proto_init() }
func file_proto_control_proto_init() {
	if File_proto_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_control_proto_rawDesc), len(file_proto_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_control_proto_goTypes,
		DependencyIndexes: file_proto_control_proto_depIdxs,
		EnumInfos:         file_proto_control_proto_enumTypes,
		MessageInfos:      file_proto_control_proto_msgTypes,
	}.Build()
	File_proto_control_proto = out.File
	file_proto_control_proto_goTypes = nil
	file_proto_control_proto_depIdxs = nil
}
